### ISSUE TITLE
大哥 你的博客怎么就挂了呢

### ISSUE THREAD

**Issue by xuqisheng** [leolord/leolord.github.io#1]
<shell+expect 前端一键部署脚本> 真的很棒 google 推荐貌似挺靠前的啦，我今天再看发现你站点关了，赶紧google 快照了～～

**Comment by leolord** [comment]
抱歉哈~ 因为实在是懒得弄了，想搬到Git Pages， 新的博文地址是：https://leolord.com/%E5%89%8D%E7%AB%AF/2016/08/16/shell+expect.html 由于某些原因，国内可能打不开，你懂的
